import MobileModule from "./module/MobileModule.js";
import AosModule from "./module/AosModule.js";
import BtnToTopModule from "./module/BtnToTopModule.js";
import PopupModule from "./module/PopupModule.js";
import SwiperModule from "./module/SwiperModule.js";
import LoadMoreModule from "./module/LoadMoreModule.js";
import CheckModule from "./module/CheckModule.js";
import GalleryModule from "./module/GalleryModule.js";
import TabModule from "./module/TabModule.js";
import HeaderModule from "./module/HeaderModule.js";
import SideModule from "./module/SideModule.js";
import ShowHideModule from "./module/ShowHideModule.js";
import OpenPopup from "./module/OpenPopup.js";
import SmoothScrollModule from "./module/SmoothScrollModule.js";
import SplitModule from "./module/SplitModule.js";
import Animated from "./module/Animated.js";
import CollapseModule from "./module/CollapseModule.js";
import scrollContent from "./module/ScrollContent.js";
import ParallaxModule from "./module/ParallaxModule.js";
import CountUpModule from "./module/CountUpModule.js";
import ScrollDesktop from "./module/ScrollDesktop.js";
import PreviewAvatar from "./module/PreviewAvatar.js";
import ConvertIframe from "./module/ConvertIframe.js";
import Select2Module from "./module/Select2Module.js";
import CountDownModule from "./module/CountDownModule.js";
import VerticalScroll from "./module/VerticalScroll.js";
import Datepicker from "./module/Datepicker.js";
import seepassword from "./module/Seepassword.js";
import RangeModule from "./module/RangeModule.js";
import PlusMinusModule from "./module/PlusMinModule.js";
import SelectCustom from "./module/SelectCustom.js";
import ItemModule from "./module/ItemModule.js";
import RatingModule from "./module/RatingModule.js";
import SelectQtyModule from "./module/SelectQtyModule.js";
import TimerModule from "./module/TimerModule.js";
import CopyModule from "./module/CopyModule.js";


window.addEventListener("DOMContentLoaded", () => {
    MobileModule();
    SplitModule()
    SwiperModule();
    AosModule();
    BtnToTopModule();
    PopupModule();
    CheckModule();
    GalleryModule();
    TabModule();
    HeaderModule();
    SideModule();
    ShowHideModule();
    OpenPopup();
    Animated();
    SmoothScrollModule();
    LoadMoreModule();
    CollapseModule();
    scrollContent();
    ParallaxModule();
    CountUpModule();
    ScrollDesktop();
    PreviewAvatar();
    ConvertIframe();
    Select2Module();
    CountDownModule();
    VerticalScroll();
    Datepicker();
    seepassword();
    RangeModule();
    PlusMinusModule();
    SelectCustom();
    ItemModule();
    RatingModule();
    SelectQtyModule();
    TimerModule();
    CopyModule();
});